// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using memberportal.Models;

namespace memberportal.Migrations
{
    [DbContext(typeof(claimsubmitcontext))]
    [Migration("20200928105228_CLAIM_TABLE_ADDED")]
    partial class CLAIM_TABLE_ADDED
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("memberportal.Models.claimsubmit", b =>
                {
                    b.Property<int>("submitid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("claimid")
                        .HasColumnType("int");

                    b.Property<string>("claimstatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("submitid");

                    b.ToTable("claimsubmits");
                });
#pragma warning restore 612, 618
        }
    }
}
